---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 1.20  Ensure a support role has been created to manage incidents with AWS Support 
    command: aws iam create-role --role-name Allada --assume-role-policy-document file://Trustpolicy.json
    tags:
      - '1.20'
      - gpgcheck
      - one
      - all
