---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 1.20  Ensure a support role has been created to manage incidents with AWS Support 
    command:  aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AWSSupportAccess --role-name Allada
    tags:
      - '1.20'
      - gpgcheck
      - one
      - all
