---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 1.4   Ensure access keys are rotated every 90 days or less    
    command: aws iam create-access-key
    tags:
      - '1.4'
      - gpgcheck
      - one
      - all
