---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.10 Ensure a log metric filter and alarm exist for security group changes  
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'SecurityGroupEvents' --metric-transformations metricName='SecurityGroupEventCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ ($.eventName = AuthorizeSecurityGroupIngress) || ($.eventName = AuthorizeSecurityGroupEgress) || ($.eventName = RevokeSecurityGroupIngress) || ($.eventName = RevokeSecurityGroupEgress) || ($.eventName = CreateSecurityGroup) || ($.eventName = DeleteSecurityGroup) }'  
    tags:
      - '3.10'
      - gpgcheck
      - one
      - all
