---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name:   Ensure a log metric filter and alarm exist for route table changes 
    ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "Routealarm"
      metric: "Routetablecount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">"
      threshold: 1
      period: 300
      evaluation_periods: 1
      unit: "Count"
      alarm_actions: ["arn:aws:cloudwatch:us-east-1:929815623526:alarm:Routealarm"]
