---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.1 Ensure a log metric filter and alarm exist for unauthorized API calls 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'APICALLS' --metric-transformations metricName='APICALLSCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ ($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*") }'
    tags:
      - '3.1'
      - gpgcheck
      - one
      - all
