---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name:  Ensure a log metric filter and alarm exist for usage of "root" account
    ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "mahialarm"
      metric: "ConsoleSignInWithoutMfaCount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">"
      threshold: 50
      period: 60
      evaluation_periods: 2
      unit: "Count"
      alarm_actions: ["arn:aws:cloudwatch:us-east-1:929815623526:alarm:mahialarm"]
