---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.2 Ensure a log metric filter and alarm exist for Management Console sign-in without MFA 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'ConsoleSignInWithoutMfa' --metric-transformations metricName='ConsoleSignInWithoutMfaCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ ($.eventName = "ConsoleLogin") && ($.additionalEventData.MFAUsed != "No") }' 
    tags:
      - '3.2'
      - gpgcheck
      - one
      - all
