---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name:  Ensure a log metric filter and alarm exist for usage of "root" account 
    ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "alladalarm"
      metric: "RootAccountUsagecount"
      namespace: "cloudtrailmetrics"
      statistic: "Minimum"
      comparison: ">"
      threshold: 1.0
      period: 60
      evaluation_periods: 2
      unit: "Count"
      description: "This will recover an instance when it fails"
      alarm_actions: ["arn:aws:cloudwatch:us-east-1:929815623526:alarm:alladalarm"]
