---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.3 Ensure a log metric filter and alarm exist for usage of root account 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'RootAccountUsage' --metric-transformations metricName='RootAccountUsageCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ $.userIdentity.type = "Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != "AwsServiceEvent" }' 
    tags:
      - '3.3'
      - gpgcheck
      - one
      - all
