---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.5  Ensure a log metric filter and alarm exist for CloudTrail configuration changes   
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'CloudTrailChanges' --metric-transformations metricName='CloudTrailEventCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern  '{ ($.eventName = CreateTrail) || ($.eventName = UpdateTrail) || ($.eventName = DeleteTrail) || ($.eventName = StartLogging) || ($.eventName = StopLogging) }'
    tags:
      - '3.4'
      - gpgcheck
      - one
      - all
