---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.7 Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'DeletionCMK' --metric-transformations metricName='DeletionCMKCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{($.eventSource = kms.amazonaws.com) && (($.eventName=DisableKey)||($.eventName=ScheduleKeyDeletion))}'  
    tags:
      - '3.7'
      - gpgcheck
      - one
      - all
