---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.8  Ensure a log metric filter and alarm exist for S3 bucket policy changes 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'S3BucketActivity' --metric-transformations metricName='S3BucketActivityEventCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ ($.eventSource = s3.amazonaws.com) && (($.eventName = PutBucketAcl) || ($.eventName = PutBucketPolicy) || ($.eventName = PutBucketCors) || ($.eventName = PutBucketLifecycle) || ($.eventName = PutBucketReplication) || ($.eventName = DeleteBucketPolicy) || ($.eventName = DeleteBucketCors) || ($.eventName = DeleteBucketLifecycle) || ($.eventName = DeleteBucketReplication)) }'  
    tags:
      - '3.8'
      - gpgcheck
      - one
      - all
