---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 3.9  Ensure a log metric filter and alarm exist for AWS Config configuration changes 
    command: aws logs put-metric-filter --log-group-name mahi --filter-name 'ConfigChange' --metric-transformations metricName='ConfigChangeCount',metricNamespace='CloudTrailMetrics',metricValue=1 --filter-pattern '{ ($.eventSource = config.amazonaws.com) && (($.eventName=StopConfigurationRecorder)||($.eventName=DeleteDeliveryChannel) ||($.eventName=PutDeliveryChannel)||($.eventName=PutConfigurationRecorder)) }'
    tags:
      - '3.9'
      - gpgcheck
      - one
      - all
