---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: create multi-region trail with validation and tags
    cloudtrail:
      state: present
      name: pad
      s3_bucket_name: harsha3 
      region: us-east-1
      is_multi_region_trail: true 
      enable_log_file_validation: true  
