---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: Password policy for AWS account
    iam_password_policy:
      state: present
      min_pw_length: 15
      require_symbols: true
      require_numbers: true
      require_uppercase: true
      require_lowercase: true
      allow_pw_change: true
      pw_max_age: 90
      pw_reuse_prevent: 24
      pw_expire: true
