---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: Create a role with description
    iam_role:
      name: mahi
      assume_role_policy_document: file:///E:\tmp/policy.json
      description: This is My New Role
